task 6 protobuf and grpc service
ozoncp/ocp-prize-api pull request #4
Opened 2021-06-09 12:43 UTC by DemiurgUrr

2021-06-09 19:21 UTC, rusdevops commented on api/ocp-prize-api/ocp-prize-api.proto
> +    // Возвращает список задач
Попрошу исправить описания - комментарии

2021-06-09 19:21 UTC, rusdevops commented on api/ocp-prize-api/ocp-prize-api.proto
> +		uint64 prize_id = 1 [(validate.rules).uint64.gt = 0];
попрошу исправить форматирование отступов

2021-06-13 08:56 UTC, siriusfreak reviewed
В общем большая часть замечаний про том, что всё нужное не генерируется просто командами make файла. 
Ещё раз -- склонируй пакет в пустую директорию и выполни все команды и проверь, что они работают так, как ожидается, то есть генерируют все файлы, пакеты, подтягивают все зависимости.
Есть вероятность, что некоторые из зависимостей глобальные. Их установку можно проверить только на чистой системе, к сожалению, либо удалив всё, что относится к go.
Такое можно сделать в докер-контейнере, взяв какой-нибудь alpine, запустившись в нём и настроив всё с нуля.
Что это даст тебе: понимание того, как работать в экосистеме модулей голанга, понимание какие команды к чему привели и когда тебе потребуется писать что-то в докер, то ты будешь знать что и откуда брать.

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
> +.generate:
Ожидаются, что будут работать команды make generate. эту цель ты можешь оставить, если от неё зависят другие.
Так можно создать ещё одну цель, типа
.PHONY: generate
generate: .generate

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
> +		ls go.mod || go mod init
Не работает, если в папке нет файла go.mod. Надо в init дописать репу твоего проекта.

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
> +.generate:
ну и вообще

`api/ocp-prize-api/ocp-prize-api.proto: Import "github.com/envoyproxy/protoc-gen-validate/validate/validate.proto" was not found or h
ad errors.
`

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
>  	golint ./...
https://github.com/golangci/golangci-lint отсюда пакет для линтера

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
>  	go run cmd/ozon-prize-api/main.go
не запускает, если не указано ./cmd/ozon-prize-api/main.go

2021-06-13 08:56 UTC, siriusfreak commented on api/ocp-prize-api/ocp-prize-api.proto
> +    uint64 issue_id = 2;
зачем с 2?

2021-06-13 08:56 UTC, siriusfreak commented on Makefile
> +		mv pkg/ocp-prize-api/gihtub.com/ozoncp/ocp-prize-api/pkg/ocp-prize-api/* pkg/ocp-prize-api/
тут не создаётся пакет go.mod

2021-06-14 10:36 UTC, siriusfreak requested changes
Изменение статуса ревью

2021-06-16 08:23 UTC, siriusfreak approved these changes

2021-06-16 08:23 UTC, merged